# Form implementation generated from reading ui file 'QTLI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# Any manWARNING: ual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog, QInputDialog, QLineEdit, QMessageBox

import sys


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(467, 282)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 461, 281))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(parent=self.widget)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_Add = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_Add.setObjectName("pushButton_Add")

        # 连接信号
        self.pushButton_Add.clicked.connect(self.add_item)

        self.verticalLayout.addWidget(self.pushButton_Add)
        self.pushButton_Edit = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_Edit.setObjectName("pushButton_Edit")

        # 连接信号
        self.pushButton_Edit.clicked.connect(self.edit_item)

        self.verticalLayout.addWidget(self.pushButton_Edit)
        self.pushButton_Remove = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_Remove.setObjectName("pushButton_Remove")

        # 连接信号
        self.pushButton_Remove.clicked.connect(self.remove_item)

        self.verticalLayout.addWidget(self.pushButton_Remove)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_Sort = QtWidgets.QPushButton(parent=self.widget)

        # 连接信号
        self.pushButton_Sort.clicked.connect(self.sort_item)

        self.pushButton_Sort.setObjectName("pushButton_Sort")
        self.verticalLayout.addWidget(self.pushButton_Sort)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def add_item(self):
        row = self.listWidget.currentRow()
        title = 'add_item'
        data, ok = QInputDialog.getText(self, title, title)

        if ok and data is not None:
            self.listWidget.insertItem(row, data)

    def edit_item(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)

        if item is not None:
            title = 'Edit Item'
            data, ok = QInputDialog.getText(self, title, title, QLineEdit.EchoMode.Normal, item.text())
            if data and ok is not None:
                item.setText(data)

    def remove_item(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)

        if item is None:
            return
        reply = QMessageBox.question(self, 'Remove Item', 'Do you want to Temove Item?',
                                     QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No)

        if reply == QMessageBox.StandardButton.Yes:
            self.listWidget.takeItem(row)

    def sort_item(self):
        self.listWidget.sortItems()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_Add.setText(_translate("Dialog", "Add"))
        self.pushButton_Edit.setText(_translate("Dialog", "Edit"))
        self.pushButton_Remove.setText(_translate("Dialog", "Remove"))
        self.pushButton_Sort.setText(_translate("Dialog", "Sort"))


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
